config/routes.rb
Rails.application.routes.draw do
  resources :juegos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/juego.rb
class Juego < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/juegos_controller.rb
class JuegosController < ApplicationController
  before_action :set_juego, only: %i[ show edit update destroy ]

  # GET /juegos or /juegos.json
  def index
    @juegos = Juego.all
  end

  # GET /juegos/1 or /juegos/1.json
  def show
  end

  # GET /juegos/new
  def new
    @juego = Juego.new
  end

  # GET /juegos/1/edit
  def edit
  end

  # POST /juegos or /juegos.json
  def create
    @juego = Juego.new(juego_params)

    respond_to do |format|
      if @juego.save
        format.html { redirect_to juego_url(@juego), notice: "Juego was successfully created." }
        format.json { render :show, status: :created, location: @juego }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @juego.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /juegos/1 or /juegos/1.json
  def update
    respond_to do |format|
      if @juego.update(juego_params)
        format.html { redirect_to juego_url(@juego), notice: "Juego was successfully updated." }
        format.json { render :show, status: :ok, location: @juego }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @juego.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /juegos/1 or /juegos/1.json
  def destroy
    @juego.destroy

    respond_to do |format|
      format.html { redirect_to juegos_url, notice: "Juego was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_juego
      @juego = Juego.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def juego_params
      params.require(:juego).permit(:nombre, :descripcion, :categoria)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/juegos_helper.rb
module JuegosHelper
end

app/views/juegos/_form.html.erb
<%= form_with(model: juego) do |form| %>
  <% if juego.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(juego.errors.count, "error") %> prohibited this juego from being saved:</h2>

      <ul>
        <% juego.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_area :descripcion %>
  </div>

  <div>
    <%= form.label :categoria, style: "display: block" %>
    <%= form.text_field :categoria %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/juegos/_juego.html.erb
<div id="<%= dom_id juego %>">
  <p>
    <strong>Nombre:</strong>
    <%= juego.nombre %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= juego.descripcion %>
  </p>

  <p>
    <strong>Categoria:</strong>
    <%= juego.categoria %>
  </p>

</div>

app/views/juegos/edit.html.erb
<h1>Editing juego</h1>

<%= render "form", juego: @juego %>

<br>

<div>
  <%= link_to "Show this juego", @juego %> |
  <%= link_to "Back to juegos", juegos_path %>
</div>

app/views/juegos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Juegos</h1>

<div id="juegos">
  <% @juegos.each do |juego| %>
    <%= render juego %>
    <p>
      <%= link_to "Show this juego", juego %>
    </p>
  <% end %>
</div>

<%= link_to "New juego", new_juego_path %>

app/views/juegos/new.html.erb
<h1>New juego</h1>

<%= render "form", juego: @juego %>

<br>

<div>
  <%= link_to "Back to juegos", juegos_path %>
</div>

app/views/juegos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @juego %>

<div>
  <%= link_to "Edit this juego", edit_juego_path(@juego) %> |
  <%= link_to "Back to juegos", juegos_path %>

  <%= button_to "Destroy this juego", @juego, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RepoGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>